name: rehoboam_neural_ui
description: A high-fidelity "Rehoboam" style neural HUD for Flutter. Features organic particulate animations, 3D Earth globe transformation, and geographic data mapping.
version: 0.0.7
homepage: https://github.com/developerashkan/rehoboam_neural_ui
repository: https://github.com/developerashkan/rehoboam_neural_ui
screenshots:
  - description: 'Main Rehoboam neural HUD visualization'
    path: assets/screenshot.png
  - description: 'Animated demo of the Rehoboam neural HUD transformation'
    path: assets/rehoboam_screen_record.gif

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  dot_globe: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
